### ISSUE TITLE
Go to Pull Request shortcut defaults to showing Go To Projects

### ISSUE THREAD

**Issue by ItsGageHolland** [stefanbuck/jumpcat#10]
### Expected Behavior

Typing `>gp` or `>g p` should show `Repository: Go to Pull Requests` as the top option

### What actually happened?

Typing `>gp` or `>g p` shows `Repository: Go to Projects` as the top option with `Repository: Go to Pull Requests` as the second

![Screenshot of problem](https://i.imgur.com/d18wqqv.jpg)

**Comment by stefanbuck** [comment]
Thanks for your feedback. I agree, this is not the expected behaviour. Let me see if I can give the pull request match more weight in that case.

**Comment by stefanbuck** [comment]
Fixed in main branch. I'm going to release a new version later this week.
