### ISSUE TITLE
Tabbing through command menu items.

### ISSUE THREAD

**Issue by lpoulter** [stefanbuck/jumpcat#11]
### Is your feature request related to a problem? Please describe.

Currently when i hit tab with the command menu Item it focuses the footer elements not the menu options.

### Describe the solution you'd like

Focus the menu options.

### Additional context

Looks like tabbing works as I'd expect for the history menu.

**Comment by stefanbuck** [comment]
Thanks Laurie for raising this issue. I'm using VSCode's command palette as a reference whenever it comes to accessibility (it is insanely good). From my observation they don't allow tabbing through the result list, maybe for the following reason. If you hit tab, the search input is losing the focus meaning you can not complete your search query without tabbing through the entire list. The command palette supports the arrow key to cycle through the list. I'm not an accessibility by any mean, but following VSCode UX/accessibility pattern is probably not a bad idea. I already disabled the foccus for the history menu which is part of 0.13.1

**Comment by clxmstaab** [comment]
> The command palette supports the arrow key to cycle through the list

maybe this key handling could somehow be made obvious in the UI?

**Comment by stefanbuck** [comment]
> maybe this key handling could somehow be made obvious/described in the UI?

Do you think this is a real concern? Most (all?) command pallets are supporting that kind of navigation nowadays. I'm worried about cluttering the UI with such hints to be honest.

**Comment by lpoulter** [comment]
I found the arrow toggle easily enough, just easier with my keyboard to tab with my left hand than arrow with my right. Don't think you need a hint.
