### ISSUE TITLE
promote jumpcat release notes

### ISSUE THREAD

**Issue by clxmstaab** [stefanbuck/jumpcat#12]
### Is your feature request related to a problem? Please describe.

when doing new releases end-users don't immediately know what changed/whats new.

### Describe the solution you'd like

you are already linking to the latest github release in the footer of jumpcat, which is great:

![image](https://user-images.githubusercontent.com/47448731/133390375-38a5aa6d-e32d-4f1b-8e79-be2da52de075.png)

I think adding a bit of marketing speech could help getting people curious and follow this link to get the latest news (or maybe the news they missed from a release before).

it could be as easy as adding something along "Release Notes" or "Whats New" after the version-string

**Comment by stefanbuck** [comment]
There is already something like that:

<img src="https://user-images.githubusercontent.com/1393946/133411847-1be8116a-1888-4fb3-99ef-37cf7e667b81.png" />


You might have visited the release page from a different page (by subscribing to release notification?) and this marks the release as read turning the footer into the default mode.

**Comment by clxmstaab** [comment]
> There is already something like that:

I am wondering why I dont see this message like that. is there a condition when it is rendered like that?
