### ISSUE TITLE
UX: guide the user in the command screen

### ISSUE THREAD

**Issue by clxmstaab** [stefanbuck/jumpcat#13]
### Is your feature request related to a problem? Please describe.

in the history menu, you are already doing a good job in guiding the user and explaining what the screen is showing to him:

![image](https://user-images.githubusercontent.com/47448731/133391035-9ad9b28f-0a5c-4f0b-9e79-9b5f3d78b25f.png)

in the command menu, this is not as good:

![image](https://user-images.githubusercontent.com/47448731/133391074-96aae0b8-d598-4bf5-8507-ae57255977d0.png)

### Describe the solution you'd like

I think this could be polished by e.g. adding a "Enter command" placeholder text (like we have a "Browse your GitHub history" placeholder in the history-screen)

**Comment by stefanbuck** [comment]
The main problem here is that the `>` sign is the actual value of the input meaning I can't use a placeholder. However, I totally agree with you and I'll try to find another solution to address this issue.

**Comment by clxmstaab** [comment]
one thing which comes to mind: maybe add a small subline below the input field which takes this text

**Comment by stefanbuck** [comment]
It will be part of the next release. Thanks for the suggestion Markus

![image](https://user-images.githubusercontent.com/1393946/133908802-c0d567f1-8430-406e-8986-181470a9d78e.png)
