### ISSUE TITLE
Add command "Merge Pull Request"

### ISSUE THREAD

**Issue by LinqLover** [stefanbuck/jumpcat#14]
### Is your feature request related to a problem? Please describe.

Given I am viewing a PR on GitHub, it would be great to have an option in the jumpcat menu to approve or to merge it, so that I do not need to use my mouse for this.

### Describe the solution you'd like

Just add the commands "Merge Pull Request", "Approve Pull Request", and maybe even "Mark as Draft"/"Mark as Ready to Review" to jumpcat.

**Comment by clxmstaab** [comment]
thinking about this a bit more: maybe jumpcat could even embedd the whole status-panel so one can see the details of all status checks and trigger the actions with the "merge-button" without the need to scroll thru all comments

![image](https://user-images.githubusercontent.com/47448731/135414366-cb78b5a4-88c0-42fb-ae29-97df5c545e73.png)

**Comment by LinqLover** [comment]
Also, there could be commands to jump to the "commits", "checks", and "changes" tabs on the top of every Pull Request ... As well as commands for closing, locking, labelling issues and PRs ...

**Comment by stefanbuck** [comment]
> Also, there could be commands to jump to the "commits", "checks", and "changes" tabs on the top of every Pull Request ... As well as commands for closing, locking, labelling issues and PRs ...

The good news, I thought about your suggestions already.
The bad news, I thought about your suggestions already.
I'm still undecided. 

I think the overall question is how much commands should Jumpcat have. Ideally every button on the UI should be covered, but I'm worried that having too many (especially less frequently used commands) will bloat the list and impact the UX badly.

Labeling issues and PRs is a tricky one (from a product perspective). In my current opinion, Jumpcat should not reimplement existing features of github.com. I see Jumpcat as an addition rather than a replacement, but I can see where you're coming from.

**Comment by LinqLover** [comment]
Thank you for the reply.

>  I'm worried that having too many (especially less frequently used commands) will bloat the list and impact the UX badly.

I am thinking of this product very much as a command palette as we have it in VS Code; i.e., overview does not matter for me, I just want to have a good search experience. I would not even complain a lot if the requested items were not visible in the empty palette but only when I starting filtering. :-) However, just my two cents ...

> Labeling issues and PRs is a tricky one (from a product perspective).

I do not have large HTML/DOM experience, but triggering a click on the "Label" button and bringing it into view might succeed ...

> In my current opinion, Jumpcat should not reimplement existing features of github.com. I see Jumpcat as an addition rather than a replacement, but I can see where you're coming from.

Maybe this project deserves its own design principles. :-) For me, having a list of as many GitHub commands as possible that I can search and use via keyboard is most important. See also: https://twitter.com/beyang/status/1441851661744365570

**Comment by stefanbuck** [comment]
You know what, I agree with you. in all points 😄  Not sure why I was thinking the list needs to be compact. Maybe so you can scan available commands quickly? Anyway, I don't do this in VSCode either, I just type and it works. 

Regarding the labeling, I thought you want to get a list of allavailablee labels inside Jumpcat. I agree, setting the focus is the way to go. GitHub does this as well with the new command palette for the new issues.

**Comment by LinqLover** [comment]
Sounds great! Looking forward to meet the new commands in jumpcat. :-)

**Comment by stefanbuck** [comment]
I added the suggested jump to "commits", "checks", and "changes" tabs commands on a pull request. The merge and labeling command needs another round of consideration/planing. I'm going to close this issue for now and will track the progress of the other commands in two separate issues.
