### ISSUE TITLE
dependabot shortcut

### ISSUE THREAD

**Issue by clxmstaab** [stefanbuck/jumpcat#17]
### Is your feature request related to a problem? Please describe.

from time to time I need to manually trigger dependabot updates.

![image](https://user-images.githubusercontent.com/47448731/137746764-dc1c94de-c658-4255-b759-115cc40ede4b.png)

therefore I need to navigation tru the repo settings to `https://github.com/$org/$repo/network/updates`
this url is hidden behind several menu layers and it requires a few clicks to get there.

### Describe the solution you'd like

a "dependabot" command to jump right into `https://github.com/$org/$repo/network/updates` of the current repo would be helpful

**Comment by stefanbuck** [comment]
At first I thought you meant those @dependabot commands to trigger a rebase, re-create... and I like this a lot 😃 

Back to your request, it's an easy thing to add. I'm going to tackle your request once I finished the current improvement regarding ranking search results.
