### ISSUE TITLE
github.com/settings/* pages appear as repositories

### ISSUE THREAD

**Issue by josephfrazier** [stefanbuck/jumpcat#5]
If I press Ctrl-K and type `settings`, items like https://github.com/settings/keys show up, but they have the `Repository` tag in front of them. I'm guessing this is because the URL looks like a repo url, and you just need to add a special case for the `settings` namespace.

**Comment by stefanbuck** [comment]
Thanks for raising this issue @josephfrazier. To be honest I've noticed that already, but since I'm in a bigger refactoring I deprioritized it. At least it's official recorded now and I'm going to fix it soon.

**Comment by stefanbuck** [comment]
This has been fixed in v0.4 (about a month ago). Sorry for the late update.
