### ISSUE TITLE
page jumps on sites with a scrollbar

### ISSUE THREAD

**Issue by clxmstaab** [stefanbuck/jumpcat#6]
### Expected Behavior

page should not jump, when jumpcat is invoked

STR
- open https://github.com/stefanbuck/jumpcat/issues/new?assignees=&labels=bug&template=bug_report.yml
- open jumpcat

### What actually happened?

scrollbar appears/disappears and therefore the website in the background shifts a few pixel left/right on open/close of the jumpcat

### Version of Jumpcat

0.3.2

**Comment by stefanbuck** [comment]
Fixed and will be part of the next release.

**Comment by clxmstaab** [comment]
fixed confirmed, thx!
