### ISSUE TITLE
Add shortcut to go to personal pull requests

### ISSUE THREAD

**Issue by Max-Leopold** [stefanbuck/jumpcat#7]
### Is your feature request related to a problem? Please describe.

Hey 👋 ,

it would be great to add a shortcut to go to my personal pull requests (https://github.com/pulls).
For me this is my Github starting page where I always go to check up on my pull requests, see if somebody requested a review etc. I know that you can do similar things from the notifications panel but I just don't use it that much.

Thanks

### Describe the solution you'd like

1. Hit `cmd` + `shift` + `K`
2. Type `pulls` (or something similar) and press enter
3. Jump to https://github.com/pulls

**Comment by stefanbuck** [comment]
Will be part of v0.5, which will land later this week. Thanks for the suggestions.
