### ISSUE TITLE
promote open-jumpcat shortcut

### ISSUE THREAD

**Issue by clxmstaab** [stefanbuck/jumpcat#8]
### Is your feature request related to a problem? Please describe.

after a great holiday I am back at work, and cannot remember the accesskey to open jumpcat.

since the only UI one can find for jumpcat is the in-browser extensions tab, it would be very helpful if this ui would indicate how to open the command palette

![image](https://user-images.githubusercontent.com/47448731/125464057-560bf1da-3b45-4235-8a49-da90a0e0a15b.png)

### Describe the solution you'd like

just a textnode like `(open with CTRL+SHIFT+P)` would be helpful.

alternatively some visual UI within the github.com main-site would be helpfull, which I can interact with to open jumpcat (so I don't need to know how to actually open the tool)

**Comment by stefanbuck** [comment]
The shortcut is <kbd>⌘</kbd><kbd>k</kbd> on mac and on windows / linux <kbd>ctrl</kbd> <kbd>k</kbd>

I totally agree that such a hint is missing. I was thinking about adding something to the UI as well (also as a reminder that Jumpcat is installed).

**Comment by clxmstaab** [comment]
> windows / linux ctrl k

pushing ctrl+k on windows also focuses the addressbar:

![image](https://user-images.githubusercontent.com/47448731/125583003-ed7d1ab6-8323-4b84-a529-7d466bab9fb2.png)

seems like a recent change in google chrome,... I can't remember seeing this problem before
using 93.0.4574.1 (Offizieller Build) canary-dcheck (32-Bit)



> I totally agree that such a hint is missing

:+1:

**Comment by stefanbuck** [comment]
Thanks for reporting Markus. I am unable to reproduce this in the latest Canary version for mac. 

Do you have Slack? They also have a command palette with the same shortcut and I wonder if this is a problem there as well.

**Comment by clxmstaab** [comment]
no slack here, sorry

**Comment by clxmstaab** [comment]
> pushing ctrl+k on windows also focuses the addressbar:

with this bug on windows the tool is unusable. are there other regular windows users of the extension?

in case this error is present on all windows systems - this would be a major blocker.

**Comment by stefanbuck** [comment]
Hi Markus, I'm aware that this prevents you from using Jumpcat, sorry about that. I'll have a look how to fix this best this weekend.

**Comment by stefanbuck** [comment]
> > pushing ctrl+k on windows also focuses the addressbar:

Fixed in https://github.com/stefanbuck/jumpcat/releases/tag/v0.5.1

**Comment by clxmstaab** [comment]
> I'm aware that this prevents you from using Jumpcat, sorry about that. I'll have a look how to fix this best this weekend.

thx for the fix - and sorry in case the previous comment sounded offensive.
just wanted to make sure you are aware that you are leaving a possible major audience behind.



> Fixed in [`v0.5.1` (release)](https://github.com/stefanbuck/jumpcat/releases/tag/v0.5.1)

confirmed, works like expected. <3.

**Comment by stefanbuck** [comment]
> thx for the fix - and sorry in case the previous comment sounded offensive.
just wanted to make sure you are aware that you are leaving a possible major audience behind.

Not at all 😄 I prefer communication straight up to the point.

**Comment by zaratan** [comment]
I think it could be useful to let the user configure their own shortcut for this. I have another extension listening for cmd-k that take precedence over jumpcat. 

See: chrome://extensions/shortcuts and https://developer.chrome.com/docs/extensions/reference/commands/ for documentation.

**Comment by stefanbuck** [comment]
Thanks, this is one of my top priorities right now. I hope to be able to release this soon.

**Comment by stefanbuck** [comment]
@zaratan are you using Firefox or Chrome? I'm asking because Firefox does not allow you to overwrite an already defined shortcut. Sounds good when reading the docs, but this actually means user have to remap e.g CMD+K (which is the shortcut to focus the address bar) just to make this work in a single website. I think the shortcuts are meant for global extensions like a password manager.

**Comment by stefanbuck** [comment]
With v0.12.0 you can remap the shortcut see [release notes](https://github.com/stefanbuck/jumpcat/releases/tag/v0.12.0). Unfortunately this feature is not supported in Firefox, due to the above mentioned reason.

**Comment by stefanbuck** [comment]
New attempt to make custom shortcuts work has been shipped with v0.13. Please have a try and let me know what do you think.

**Comment by clxmstaab** [comment]
I like it
