### ISSUE TITLE
version infos.. 

### ISSUE THREAD

**Issue by clxmstaab** [stefanbuck/jumpcat#9]
### Expected Behavior

I am wondering why I have jumpcat version 0.5, although version 0.4 was recently released.

I guess this version came back from the future? :)
![image](https://user-images.githubusercontent.com/47448731/126122446-a45a7f11-e349-4374-b6e6-c005b9de2b27.png)

### What actually happened?

extension menu should show 0.4, I guess?

**Comment by clxmstaab** [comment]
btw: is this ID in the menu security sensitive? or is it just the fingerprint of the extension?

**Comment by stefanbuck** [comment]
Forgot to hit the publish button on the release draft 🤦 https://github.com/stefanbuck/jumpcat/releases/tag/v0.5.0.

The screenshot just shows the id of the extensions, so all good
